#![allow(dead_code)]
use sokol::gfx as sg;
/*
    #version:1# (machine generated, don't edit!)

    Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

    Cmdline:
        sokol-shdc -i ./src/shaders/circ_shader.glsl -o ./src/compiled_shaders/circ_shader.rs --slang hlsl5:wgsl:glsl430 -f sokol_rust

    Overview:
    =========
    Bindings:
*/
